application: sumedhapersonalwebsite
version: 1
runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /contact.php
  script: contact.php

- url: /.*
  script: myweb.php

- url: /
  script: myweb.php